---
containers:
  keystone:
    image: 'keystone:mitaka-cf3b389'
    extra_params:
      - '--network=host'
      - '--add-host=compute.datacentred.io:192.168.237.133'
      - '--add-host=osdbmq0.vagrant.test:192.168.237.132'
  glance:
    image: 'glance:mitaka-91d7999'
    volumes:
      - '/var/lib/glance'
    extra_params:
      - '--network=host'
      - '--add-host=compute.datacentred.io:192.168.237.133'
      - '--add-host=osdbmq0.vagrant.test:192.168.237.132'
  cinder:
    image: 'cinder:mitaka-5452976'
    extra_params:
      - '--network=host'
      - '--add-host=compute.datacentred.io:192.168.237.133'
      - '--add-host=osdbmq0.vagrant.test:192.168.237.132'
  nova:
    image: 'nova:liberty-f686d93'
    extra_params:
      - '--network=host'
      - '--add-host=compute.datacentred.io:192.168.237.133'
      - '--add-host=osdbmq0.vagrant.test:192.168.237.132'
  neutron:
    image: 'neutron:liberty-0ae683d'
    extra_params:
      - '--network=host'
      - '--add-host=compute.datacentred.io:192.168.237.133'
      - '--add-host=osdbmq0.vagrant.test:192.168.237.132'
  horizon:
    image: 'horizon:mitaka-fd22a1a'
    extra_params:
      - '--network=host'
      - '--add-host=compute.datacentred.io:192.168.237.133'
      - '--add-host=osdbmq0.vagrant.test:192.168.237.132'
