---
dc_elasticsearch::ssd_drives:
  - '/var/storage/ssd_01'
dc_elasticsearch::hdd_drives:
  - '/var/storage/hdd_01'
dc_elasticsearch::es_hash:
  bootstrap.memory_lock: true
  cloud.aws.s3.endpoint: ''
  cluster.name: 'logstash_platform_services'
  discovery.zen.minimum_master_nodes: 1
  discovery.zen.ping.unicast.hosts:
    - "elasticsearch0.%{::domain}"
  indices.memory.index_buffer_size: '50%'
  network.host:
    - '_local_'
    - "%{::ipaddress}"
  node.master: true
  node.data: true
  xpack.security.enabled: false
