---
puppet::conf:
  main:
    logdir: '/var/lib/puppet'
    vardir: '/var/lib/puppet'
    ssldir: '/var/lib/puppet/ssl'
    rundir: '/var/run/puppet'
    show_diff: 'true'
    dns_alt_names: '*,*.example.com,*.staging.datacentred.services'

dc_profile::net::core_gateway::frontends: {}
dc_profile::net::core_gateway::backends: {}
dc_profile::net::core_gateway::listeners: {}
dc_profile::net::core_gateway::balancermembers: {}
