#!/usr/bin/env python

import subprocess
import sys
import syslog
import re
import os
import signal
import time

def main(argv):
	threshold = argv[0]
	output = subprocess.check_output(['ps', '-eo', 'pid,etimes,args'])
	for line in re.split(r'\n', output):
		fields = re.split(r'\s+', line.lstrip())
		if len(fields) < 3:
			continue
		pid = fields[0]
		etimes = fields[1]
		cmd = fields[2]
		if (cmd == '/usr/bin/ipmitool') and (int(etimes) > int(threshold)):
			os.kill(int(pid), signal.SIGKILL)
			time.sleep(1)
			subprocess.call(['/sbin/modprobe', '-r', 'ipmi_si'])
			subprocess.call(['/sbin/modprobe', 'ipmi_si'])
			syslog.syslog(
				syslog.LOG_NOTICE,
				'ipmi_reaper has harvested a soul'
			)

if __name__ == '__main__':
	main(sys.argv[1:])

# vi: ts=4 noet:
