#!/usr/bin/env python

"""
Performs a firmware revision check against the specified host with a specific
username and password combination
"""

import argparse
import re
import subprocess
import sys

NAGIOS_OK = 0
NAGIOS_WARNING = 1
NAGIOS_CRITICAL = 2
NAGIOS_UNKNOWN = 3

def main():
    """Checks the firmware revision with ipmitool"""

    parser = argparse.ArgumentParser()
    parser.add_argument('-H', '--host', required=True)
    parser.add_argument('-u', '--username', required=True)
    parser.add_argument('-p', '--password', required=True)
    parser.add_argument('-r', '--revision', required=True)
    args = parser.parse_args()

    command = [
        'ipmitool',
        '-I', 'lanplus',
        '-H', args.host,
        '-U', args.username,
        '-P', args.password,
        'mc',
        'info',
    ]

    try:
        output = subprocess.check_output(command, stderr=subprocess.PIPE)
    except subprocess.CalledProcessError:
        print 'CRITICAL: Unable to contact BMC'
        sys.exit(NAGIOS_CRITICAL)

    revision_real = re.findall(r'Firmware Revision\s+:\s+(\S+)', output)[0]
    if revision_real != args.revision:
        print 'WARNING: Revision mismatch, expected={}, actual={}'.format(
            args.revision, revision_real)
        sys.exit(NAGIOS_WARNING)

    print 'OK'
    sys.exit(NAGIOS_OK)

if __name__ == '__main__':
    main()
