#! /bin/bash
# check_netfilter.nf_conntrack.sh nagios plugin
#
# by Jeronimo Zucco <jczucco+nagios@gmail.com>
# April/20/2012
#
# This Nagios plugin was created to check the status of netfilter conntrack table
#
# sysctl net.netfilter.nf_conntrack_count : check the number of connections in table
# sysctl net.netfilter.nf_conntrack_max : check the max size of netfilter conntrack table
#
# Licence: "GNU Public License v2"
# Dependencies: expr, grep, sed
#
# If you are running a Linux firewall, you should be using this script ;-)
# 
# nagiosgraph map:
# /output:Conntrack Tables.*?(\d+)\n/
# and push @s, [ 'conntrack',
#                [ 'entries', GAUGE, $1 ] ];

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

PROGNAME=`basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION="0.2"
VERBOSE=false
WARNING=""
CRITICAL=""

print_usage() {
  echo "Usage:"
  echo "  $PROGNAME -w WARNING% -c CRITICAL%"
  echo "  $PROGNAME -h"
  echo "  $PROGNAME -v"
}

print_help() {
  print_revision $PROGNAME $REVISION
  echo ""
  print_usage
  echo ""
  echo "Check netfilter conntrack table status"
  echo ""
  echo "The percs are based in net.netfilter.nf_conntrack_max and net.netfilter.nf_conntrack_count"
  echo ""
  echo "-w Warning percent level" 
  echo "-c Critical percent level"
  echo "-h Print this help screen"
  echo "-v Print version and license information"
}

while getopts 'w:c:vh' opt; do
  case $opt in
    w) WARNING=${OPTARG};;
    c) CRITICAL=${OPTARG};;
    v) echo $PROGNAME $REVISION;;
    h) print_help;;
    ?/) print_usage;;
  esac
done

if [ -z $WARNING ] || [ -z $CRITICAL ]
then
    echo "Both warning and critical values must be provided"
    print_usage
    exit
else
        USED=$(sysctl -n net.netfilter.nf_conntrack_count)
        MAX=$(sysctl -n net.netfilter.nf_conntrack_max)

        if [ ${MAX} -gt 0 ]; then
                AUX=$(expr ${USED} \* 100 / ${MAX} )
                PERF="conn=${AUX}%;${WARNING};${CRITICAL};0;100"

                if [ ${AUX} -lt ${WARNING} ]; then
                        echo "Conntrack Tables OK - ${USED} (${AUX}%) | ${PERF}"
                        exit $STATE_OK
                else
                        if [ ${AUX} -ge ${CRITICAL} ]; then
                                echo "Conntrack Tables CRITICAL - ${USED} (${AUX}%) | ${PERF}"
                                exit $STATE_CRITICAL
                        else
                                if [ ${AUX} -ge ${WARNING} ]; then
                                        echo "Conntrack Tables WARNING - ${USED} (${AUX}%) | ${PERF}"
                                        exit $STATE_WARNING
                                fi
                        fi
                fi
        else 
                echo "Can't check net.netfilter.nf_conntrack_max"
                exit $STATE_UNKNOWN
        fi
fi

