#!/usr/bin/env python
"""
Check Ceph Cluster Health Status
"""

import json
import socket
import subprocess
import sys


NAGIOS_OK = 0
NAGIOS_WARNING = 1
NAGIOS_CRITICAL = 2
NAGIOS_UNKNOWN = 3


def ceph_health():
    """Get the ceph health status"""

    command = ['ceph', 'health', '-f', 'json']
    try:
        output = subprocess.check_output(command)
    except subprocess.CalledProcessError:
        print 'UNKNOWN: unable to read health status'
        sys.exit(NAGIOS_UNKNOWN)
    return json.loads(output)


def main():
    """Check the cluster health if the elected leader"""

    health = ceph_health()

    # Do I need to do the checking?
    name = socket.gethostname()
    leader = health['health']['health_services'][0]['mons'][0]['name']
    if leader != name:
        print 'OK: {} elected leader'.format(leader)
        sys.exit(NAGIOS_OK)

    # Convert from Ceph speak into internal language
    code = {
        'HEALTH_OK': NAGIOS_OK,
        'HEALTH_WARN': NAGIOS_WARNING,
        'HEALTH_ERR': NAGIOS_CRITICAL,
    }[health['overall_status']]

    # Print out the summary line and any additonal detail
    print ['OK', 'Warning', 'Critical'][code]
    if code != NAGIOS_OK:
        for summary in health['summary']:
            print '{}: {}'.format(summary['severity'], summary['summary'])

    return code


if __name__ == '__main__':
    main()

# vi: ts=4 et:
