#!/usr/bin/env python
"""
Monitors the liveness of the server
"""

import argparse
import base64
import httplib
import json
import sys
import urllib

NAGIOS_OK = 0
NAGIOS_WARNING = 1
NAGIOS_CRITICAL = 2
NAGIOS_UNKNOWN = 3


def rabbit_request(args, urn):
    """Performs the API request against the specified URN"""

    auth = 'Basic ' + base64.b64encode(args.username + ':' +args.password)

    connection = httplib.HTTPConnection(args.hostname, args.port)
    connection.request('GET', urn, headers={'Authorization': auth})
    response = connection.getresponse()
    if response.status != 200:
        print 'UNKNOWN: unable to contact server'
        sys.exit(NAGIOS_UNKNOWN)

    return json.loads(response.read())


def main():
    """Performs an aliveness test API call"""

    parser = argparse.ArgumentParser()
    parser.add_argument('-H', '--hostname', required=True)
    parser.add_argument('-P', '--port', required=True)
    parser.add_argument('-u', '--username', required=True)
    parser.add_argument('-p', '--password', required=True)
    parser.add_argument('-V', '--vhost', required=True)
    args = parser.parse_args()

    # Encode vhosts e.g. / becomes %2F
    vhost = urllib.quote(args.vhost, '')

    # Perform the API call
    urn = '/api/aliveness-test/' + vhost
    result = rabbit_request(args, urn)

    # Perform error checking
    code = NAGIOS_OK
    if result['status'] != 'ok':
        code = NAGIOS_CRITICAL

    # Perform output
    status = ['OK', 'WARNING', 'CRITICAL'][code]
    print '{}: status {}'.format(status, result['status'])

    sys.exit(NAGIOS_OK)


if __name__ == '__main__':
    main()

# vi: ts=4 et:
