#!/usr/bin/env python
"""
Checks basic TFTP functionality
"""

# pylint: disable=import-error

import argparse
import sys
import tftpy
import time

NAGIOS_OK = 0
NAGIOS_WARNING = 1
NAGIOS_CRITICAL = 2
NAGIOS_UNKNOWN = 3


def main():
    """Checks the PXE path can be accessed over TFTP"""

    parser = argparse.ArgumentParser()
    parser.add_argument('-H', '--hostname', default='localhost')
    parser.add_argument('-p', '--port', default=69)
    parser.add_argument('-u', '--url', required=True)
    args = parser.parse_args()

    client = tftpy.TftpClient(args.hostname, args.port)
    start = time.time()
    try:
        client.download(args.url, '/dev/null')
    except tftpy.TftpShared.TftpException:
        print 'CRITICAL: unable to access {}'.format(args.url)
        sys.exit(NAGIOS_CRITICAL)
    end = time.time()
    delta = end - start

    print 'OK: downloaded {0} in {1:.3f}s | time={1:.3f}s'.\
          format(args.url, delta)


if __name__ == '__main__':
    main()

# vi: ts=4 et:
