---
listeners:
  haproxy-stats:
    mode: 'http'
    bind:
      ':1936':
        - 'ssl'
        - 'no-sslv3'
        - 'ciphers EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5'
        - 'crt /etc/ssl/private/puppet.crt'
        - 'ca-file /var/lib/puppet/ssl/certs/ca.pem'
        - 'verify required'
    options:
      stats:
        - 'enable'
        - 'uri /'
      rspadd: 'Strict-Transport-Security:\ max-age=31536000'
  galera:
    ipaddress: "%{hiera('os_api_vip')}"
    mode: 'tcp'
    ports: '3306'
    options:
      option:
        - 'httpchk'
      balance: 'source'
      'timeout client': '8h'
      'timeout server': '8h'
