---
dc_elasticsearch::ssd_drives:
  - '/var/storage/ssd_01'
  - '/var/storage/ssd_02'
dc_elasticsearch::hdd_drives:
  - '/var/storage/hdd_01'
  - '/var/storage/hdd_02'
  - '/var/storage/hdd_03'
  - '/var/storage/hdd_04'
dc_elasticsearch::es_hash:
  bootstrap.memory_lock: true
  cloud.aws.s3.endpoint: 'storage.datacentred.io'
  cluster.name: 'logstash_platform_services'
  discovery.zen.minimum_master_nodes: 2
  discovery.zen.ping.multicast.enabled: false
  discovery.zen.ping.unicast.hosts:
    - "elasticsearch0.%{::domain}"
    - "elasticsearch1.%{::domain}"
    - "elasticsearch2.%{::domain}"
  indices.memory.index_buffer_size: '50%'
  network.host:
    - '_local_'
    - "%{::ipaddress}"
  node.master: true
  node.data: true
  thread_pool.index.queue_size: 200
  thread_pool.index.size: 4
  thread_pool.search.queue_size: '100'
  thread_pool.search.size: 20
