---
classes:
  - '::dc_profile::ceph::radosgw_lb'

haproxy::defaults_options:
  log: 'global'
  stats: 'enable'
  option: 'redispatch'
  retries: '3'
  timeout:
    - 'http-request 10s'
    - 'queue 1m'
    - 'connect 10s'
    - 'client 30m'
    - 'server 30m'
    - 'check 10s'
  maxconn: '8000'
