---
classes:
  - '::dc_profile::ceph::radosgw_lb'

haproxy::package_ensure: '1.5.14-1ubuntu0.15.10.1~ubuntu14.04.1'
haproxy::defaults_options:
  log: 'global'
  stats: 'enable'
  option: 'redispatch'
  retries: '3'
  timeout:
    - 'http-request 10s'
    - 'queue 1m'
    - 'connect 10s'
    - 'client 30m'
    - 'server 30m'
    - 'check 10s'
  maxconn: '8000'

dc_nrpe::checks::net_interfaces::exclude: 'p1p2'

filebeat::prospectors:
  haproxy:
    paths:
      - '/var/log/haproxy.log'
    doc_type: 'haproxy'
