---
classes:
  - '::dc_profile::ceph::radosgw'

ceph::rgw: true

ceph::conf:
  global:
    rgw region: 'uk'
    rgw zone: 'uk-sal01'
  client.rgw.%{hostname}:
    host: "%{hostname}"
    rgw enable ops log: 'true'
    rgw enable usage log: 'true'
    rgw thread pool size: '4096'
    rgw dns name: 'storage.datacentred.io'
    rgw socket path: "/var/run/ceph/ceph.client.radosgw.%{hostname}.fastcgi.sock"
    rgw keystone url: 'https://compute.datacentred.io:35357'
    rgw keystone admin token: 'b87a49b7-7297-43f7-8a95-7ca26f0516ff'
    rgw keystone accepted roles: '_member_,admin'
    rgw relaxed s3 bucket names: 'true'
    rgw print prohibited content length: 'true'
    rgw swift account in url: 'true'


ceph::keys:
  /etc/ceph/ceph.client.admin.keyring:
    user: 'client.admin'
    key: "%{hiera('ceph_key_client_admin')}"
  /var/lib/ceph/bootstrap-rgw/ceph.keyring:
    user: 'client.bootstrap-rgw'
    key: "%{hiera('ceph_key_bootstrap_rgw')}"

apache::default_vhost: false
apache::log_formats:
    radosgw: '\"%%{}{X-Forwarded-For}i\" %l %u %t \"%r\" %>s %b \"%%{}{Referer}i\" \"%%{}{User-Agent}i\"'
apache::trace_enable: 'Off'

dc_nrpe::checks::net_interface::excluded_ints:
  - 'p1p1'
