---
classes:
  - '::dc_profile::ceph::mon'

ceph::mon: true

ceph::conf:
  mon:
    mon compact on start: 'true'
    mon compact on trim: 'true'

ceph::keys:
  /etc/ceph/ceph.client.admin.keyring:
    user: 'client.admin'
    key: "%{hiera('ceph_key_client_admin')}"
    caps_mon: 'allow *'
    caps_osd: 'allow *'
    caps_mds: 'allow'
  /var/lib/ceph/bootstrap-osd/ceph.keyring:
    user: 'client.bootstrap-osd'
    key: "%{hiera('ceph_key_bootstrap_osd')}"
    caps_mon: 'allow profile bootstrap-osd'
  /var/lib/ceph/bootstrap-rgw/ceph.keyring:
    user: 'client.bootstrap-rgw'
    key: "%{hiera('ceph_key_bootstrap_rgw')}"
    caps_mon: 'allow profile bootstrap-rgw'
  /var/lib/ceph/bootstrap-mds/ceph.keyring:
    user: 'client.bootstrap-mds'
    key: "%{hiera('ceph_key_bootstrap_mds')}"
    caps_mon: 'allow profile bootstrap-mds'
  /etc/ceph/ceph.client.cinder.keyring:
    user: 'client.cinder'
    key: "%{hiera('ceph_key_client_cinder')}"
    caps_mon: 'allow r'
    caps_osd: 'allow class-read object_prefix rbd_children, allow rwx pool=cinder.volumes, allow rwx pool=cinder.volumes.flash, allow rwx pool=cinder.vms, allow rx pool=glance'
  /etc/ceph/ceph.client.glance.keyring:
    user: 'client.glance'
    key: "%{hiera('ceph_key_client_glance')}"
    caps_mon: 'allow r'
    caps_osd: 'allow class-read object_prefix rbd_children, allow rwx pool=glance'

sysctls::values:
    fs.file-max:
        value: '4096000'
    net.core.rmem_max:
        value: '67108864'
    net.core.wmem_max:
        value: '67108864'
    net.core.rmem_default:
        value: '33554432'
    net.core.wmem_default:
        value: '33554432'
    net.ipv4.tcp_rmem:
        value: '16384 87380 6291456'
    net.ipv4.tcp_wmem:
        value: '16384 32768 4194304'
    net.ipv4.udp_rmem_min:
        value: '16384'
    net.ipv4.udp_wmem_min:
        value: '16384'
    net.core.optmem_max:
        value: '65536'
    net.ipv4.tcp_low_latency:
        value: '1'
    net.ipv4.tcp_window_scaling:
        value: '1'
    net.ipv4.tcp_slow_start_after_idle:
        value: '0'
    net.ipv4.tcp_no_metrics_save:
        value: '1'
    net.ipv4.tcp_sack:
        value: '0'
    net.core.somaxconn:
        value: '8192'
    net.ipv4.tcp_max_syn_backlog:
        value: '8192'
    net.ipv4.tcp_syncookies:
        value: '1'
    net.core.netdev_max_backlog:
        value: '32768'
    net.ipv4.tcp_fin_timeout:
        value: '15'
    net.ipv4.tcp_max_tw_buckets:
        value: '131072'
    net.ipv4.tcp_tw_reuse:
        value: '1'
    net.ipv4.tcp_timestamps:
        value: '1'
    net.ipv4.tcp_keepalive_time:
        value: '120'
    net.ipv4.tcp_keepalive_intvl:
        value: '30'
    net.ipv4.tcp_keepalive_probes:
        value: '3'
    net.ipv4.ip_local_port_range:
        value: '16384 65000'
    vm.swappiness:
        value: '10'
