---
classes:
  - 'dc_profile::net::dns_master'
  - 'dc_profile::net::foreman_checks'
  - 'dc_profile::auth::radius::server'

ntp::servers:
  - '0.uk.pool.ntp.org'
  - '1.uk.pool.ntp.org'
  - '2.uk.pool.ntp.org'
  - '3.uk.pool.ntp.org'
ntp::autoupdate: false
# Caution - although this mirrors the class params defaults we need to
# override the class defaults defined in hiera
ntp::restrict:
  - 'default kod nomodify notrap nopeer noquery'
  - '-6 default kod nomodify notrap nopeer noquery'
  - '127.0.0.1'
  - '-6 ::1'
ntp::interfaces:
  - "%{::ipaddress}"

dc_dhcp::zonemaster: '127.0.0.1'

dc_ssh::config:
  AllowGroups:
    value:
      - 'dhcp_sync_agent'
      - 'tftpsync'

foreman_proxy::http: true
foreman_proxy::http_port: '8000'
foreman_proxy::puppet: false
foreman_proxy::puppetca: false
foreman_proxy::puppet_group: 'puppet'
foreman_proxy::groups:
  - 'tftp'
  - 'bind'
foreman_proxy::templates: true
foreman_proxy::templates_listen_on: 'both'
foreman_proxy::templates_url: "http://%{::fqdn}:8000"
foreman_proxy::tftp: true
foreman_proxy::tftp_listen_on: 'https'
foreman_proxy::tftp_managed: false
foreman_proxy::tftp_root: '/var/tftpboot'
foreman_proxy::dhcp: true
foreman_proxy::dhcp_managed: false
foreman_proxy::dhcp_listen_on: 'https'
foreman_proxy::dhcp_provider: 'isc'
foreman_proxy::dhcp_config: '/etc/dhcp/dhcpd.conf'
foreman_proxy::dhcp_leases: '/var/lib/dhcp/dhcpd.leases'
foreman_proxy::dhcp_key_name: "%{hiera('omapi_key')}"
foreman_proxy::dhcp_key_secret: "%{hiera('omapi_secret')}"
foreman_proxy::dns: true
foreman_proxy::dns_managed: false
foreman_proxy::dns_listen_on: 'https'
foreman_proxy::dns_provider: 'nsupdate'
foreman_proxy::dns_key: '/etc/bind/rndc.key'
foreman_proxy::bmc: true
foreman_proxy::bmc_listen_on: 'https'
foreman_proxy::bmc_default_provider: 'ipmitool'
