---
classes:
  - '::dc_profile::foreman::foreman'
apache::mod::passenger::mod_package_ensure: '1:5.0.16-1~trusty1'
apache::mod::passenger::passenger_max_pool_size: '10'
apache::mod::passenger::passenger_max_requests: '1000'
apache::mod::passenger::passenger_high_performance: 'on'
