---
classes:
  - '::dc_profile::foreman::foreman'
apache::mod::passenger::passenger_max_pool_size: '7'
apache::mod::passenger::passenger_max_requests: '1000'
apache::mod::passenger::passenger_high_performance: 'on'

sysctls::values:
    vm.swappiness:
        value: '1'

memcached::listen_ip: "%{::ipaddress}"
