---
classes:
  - '::dc_profile::net::core_gateway'

puppet::conf:
  main:
    logdir: '/var/lib/puppet'
    vardir: '/var/lib/puppet'
    ssldir: '/var/lib/puppet/ssl'
    rundir: '/var/run/puppet'
    dns_alt_names: 'puppet,puppet.core.sal01.datacentred.co.uk,puppet.datacentred.services,puppetdb,puppetdb.core.sal01.datacentred.co.uk,foreman,foreman.core.sal01.datacentred.co.uk,foreman.datacentred.services'
