---
classes:
  - '::dc_profile::net::core_gateway'

puppet::conf:
  main:
    logdir: '/var/lib/puppet'
    vardir: '/var/lib/puppet'
    ssldir: '/var/lib/puppet/ssl'
    rundir: '/var/run/puppet'
    show_diff: 'true'
    dns_alt_names: '*,*.core.sal01.datacentred.co.uk,*.datacentred.services'

# WAN interface runs at internet MTU of 1500
dc_nrpe::checks::net_interfaces::exclude: '^em2$'

# Timeouts are important here
# - Server time out: log running things like foreman/puppet
# - Client time out: persistent connections such as log shippers
haproxy::defaults_options:
  log: 'global'
  stats: 'enable'
  option: 'redispatch'
  retries: '3'
  timeout:
    - 'http-request 10s'
    - 'queue 1m'
    - 'connect 10s'
    - 'client 5m'
    - 'server 5m'
    - 'check 10s'
  maxconn: '8000'

# Remove services that clash with ports the gateway is listening on
excludes:
  - '::dc_profile::mon::icinga2'
