---
classes:
  - '::dc_profile::net::core_gateway'

# Remove services that clash with ports the gateway is listening on
excludes:
  - '::dc_profile::mon::icinga2'

# Timeouts are important here
# - Server time out: log running things like foreman/puppet
# - Client time out: persistent connections such as log shippers
haproxy::defaults_options:
  log: 'global'
  stats: 'enable'
  option: 'redispatch'
  retries: '3'
  timeout:
    - 'http-request 10s'
    - 'queue 1m'
    - 'connect 10s'
    - 'client 5m'
    - 'server 5m'
    - 'check 10s'
  maxconn: '8000'
  tune.ssl.default-dh-param: '2048'
