---
classes:
  -  '::dc_profile::net::phpipam'
  -  '::dc_profile::db::duplicity_mariadb'

databases:
  "%{hiera('phpipam::db_name')}":
    user:     "%{hiera('phpipam::db_user')}"
    password: "%{hiera('phpipam::db_pass')}"

apache::mpm_module: 'prefork'

php::extensions:
  mysql: {}
  ldap: {}
