---
classes:
  - '::dc_profile::ci::jenkins'
  - '::dc_docker::client'
  - '::dc_docker::rocker'
  - '::dc_profile::util::unattended_upgrades'

puppetdeploy::is_jenkins: true

telegraf::inputs:
  docker:
    endpoint: "unix:///var/run/docker.sock"

telegraf_groups:
  - 'puppet'
  - 'docker'
