---
classes:
 - '::nfsen'
apache::default_vhost: false
apache::mpm_module: 'prefork'
nfsen::basedir: '/var/lib/nfsen'
nfsen::htmldir: '/var/www/html/nfsen/'
nfsen::subdirlayout: 1
nfsen::mail_from: "netflow@%{::fqdn}"
nfsen::custom_repo: true
nfsen::custom_repo_source: 'https://github.com/millingworth/nfsen'
nfsen::web_ssl_verify_client: 'require'
nfsen::web_ssl_verify_depth: 1
