---
classes:
  -  '::dc_profile::net::network_monitoring_master'
zabbix::zabbix_url: 'zabbix-server.vagrant.test'
zabbix::database_type: 'postgresql'
zabbix::manage_vhost: false
zabbix::manage_firewall: true
zabbix::zabbix_timezone: 'Europe/London'
zabbix::agent::server: '127.0.0.1'
zabbix::agent::listenip: '127.0.0.1'
zabbix::agent::manage_resources: true
zabbix::manage_resources: true
