---
classes:
  -  '::dc_profile::net::network_monitoring_satellite'

apache::mpm_module: 'prefork'
firewall::purge: true

rsyslog::client::listen_localhost: false
rsyslog::client::custom_config: 'dc_rsyslog/network_monitoring_satellite_rsyslog.conf.erb'

rsyslog::client::log_templates:
  - name: 'arkngPerHostLog'
    template: '/var/log/network/ark-ng/%HOSTNAME%.log'
  - name: 'arkPerHostLog'
    template: '/var/log/network/ark/%HOSTNAME%.log'
  - name: 'corePerHostLog'
    template: '/var/log/network/core/%HOSTNAME%.log'
  - name: 'dcimPerHostLog'
    template: '/var/log/network/dcim/%HOSTNAME%.log'
  - name: 'stagePerHostLog'
    template: '/var/log/network/stage/%HOSTNAME%.log'



rsyslog::client::log_filters:
  - expression: '$fromhost-ip startswith "10.10.32."'
    action: "-?arkPerHostLog\n&~"
  - expression: '$fromhost-ip startswith "10.20.32."'
    action: "-?stagePerHostLog\n&~"
  - expression: '$fromhost-ip startswith "10.30.32."'
    action: "-?corePerHostLog\n&~"
  - expression: '$fromhost-ip startswith "10.35.32."'
    action: "-?dcimPerHostLog\n&~"
  - expression: '$fromhost-ip startswith "10.40.32."'
    action: "-?arkngPerHostLog\n&~"
 
