---
classes:
  - '::dc_profile::openstack::neutron::agent_network'
  - '::dc_icinga::hostgroup_neutron_node'

neutron::debug: true

sudo::configs:
  neutron:
    content: |
      Defaults:neutron !requiretty, syslog_badpri=err, syslog_goodpri=info
      neutron ALL=(root) NOPASSWD: /usr/bin/neutron-rootwrap

sysctls::values:
    fs.file-max:
        value: '4096000'
    net.core.rmem_max:
        value: '67108864'
    net.core.wmem_max:
        value: '67108864'
    net.core.rmem_default:
        value: '33554432'
    net.core.wmem_default:
        value: '33554432'
    net.ipv4.tcp_rmem:
        value: '16384 87380 6291456'
    net.ipv4.tcp_wmem:
        value: '16384 32768 4194304'
    net.ipv4.udp_rmem_min:
        value: '16384'
    net.ipv4.udp_wmem_min:
        value: '16384'
    net.core.optmem_max:
        value: '65536'
    net.ipv4.tcp_low_latency:
        value: '1'
    net.ipv4.tcp_window_scaling:
        value: '1'
    net.ipv4.tcp_slow_start_after_idle:
        value: '0'
    net.ipv4.tcp_no_metrics_save:
        value: '1'
    net.ipv4.tcp_sack:
        value: '0'
    net.core.somaxconn:
        value: '8192'
    net.ipv4.tcp_max_syn_backlog:
        value: '8192'
    net.ipv4.tcp_syncookies:
        value: '1'
    net.core.netdev_max_backlog:
        value: '32768'
    net.ipv4.tcp_fin_timeout:
        value: '15'
    net.ipv4.tcp_max_tw_buckets:
        value: '131072'
    net.ipv4.tcp_tw_reuse:
        value: '1'
    net.ipv4.tcp_timestamps:
        value: '1'
    net.ipv4.tcp_keepalive_time:
        value: '120'
    net.ipv4.tcp_keepalive_intvl:
        value: '30'
    net.ipv4.tcp_keepalive_probes:
        value: '3'
    net.ipv4.ip_local_port_range:
        value: '16384 65000'
    net.nf_conntrack_max:
        value: '1048576'
    vm.swappiness:
        value: '10'

telegraf::inputs:
  nstat:
    proc_net_netstat: '/proc/net/netstat'
    proc_net_snmp: '/proc/net/snmp'
    proc_net_snmp6: '/proc/net/snmp6'
