---
classes:
  - '::dc_profile::openstack::keystone'
  - '::dc_profile::openstack::glance'
  - '::dc_profile::openstack::cinder'
  - '::dc_profile::openstack::neutron::server'
  - '::dc_profile::openstack::nova::control'
  - '::dc_profile::openstack::ceilometer::control'
  - '::dc_profile::openstack::aodh'
  - '::dc_profile::openstack::heat'
  - '::dc_profile::openstack::horizon'
  - '::dc_profile::log::rsyslog_client'
  - '::dc_profile::openstack::docker::logging'
  - '::dc_docker::client'
  - '::sysctls'

dc_icinga2_plugins::modules:
  - '::dc_icinga2_plugins::modules::openstack_control'

# Increase number of file handles
#
sysctls::values:
    fs.file-max:
        value: '4096000'

neutron::debug: true

sudo::configs:
  nova:
    content: |
      Defaults: nova !requiretty
      nova ALL=(root) NOPASSWD: /usr/bin/nova-rootwrap
  neutron:
    content: |
      Defaults:neutron !requiretty, syslog_badpri=err, syslog_goodpri=info
      neutron ALL=(root) NOPASSWD: /usr/bin/neutron-rootwrap

dc_ssh::config:
  AllowGroups:
    value:
      - 'nova'

ceph::keys:
  /etc/ceph/ceph.client.cinder.keyring:
    user: 'client.cinder'
    key: "%{hiera('ceph_key_client_cinder')}"
  /etc/ceph/ceph.client.glance.keyring:
    user: 'client.glance'
    key: "%{hiera('ceph_key_client_glance')}"

ceph::user: 'root'
ceph::group: 'root'

# Stop Apache claiming ownership of port 80
#
apache::default_vhost: false

# Set MPM worker to 'Event'
apache::mpm_module: 'event'

# Docker container definitions
#
containers:
  keystone:
    image: 'registry.datacentred.services:5000/sal01.datacentred.co.uk/keystone:6d55b1d'
  glance:
    image: 'registry.datacentred.services:5000/sal01.datacentred.co.uk/glance:cce7799'
    volumes:
      - '/var/lib/glance'
  cinder:
    image: 'registry.datacentred.services:5000/cinder:mitaka-5452976'
  horizon:
    image: 'registry.datacentred.services:5000/sal01.datacentred.co.uk/horizon:ba9e3b1'
  nova:
    image: 'registry.datacentred.services:5000/sal01.datacentred.co.uk/nova:6e05bf3'
  neutron:
    image: 'registry.datacentred.services:5000/sal01.datacentred.co.uk/neutron:42792f0'
  ceilometer:
    image: 'registry.datacentred.services:5000/sal01.datacentred.co.uk/ceilometer:57dc6a5'
  aodh:
    image: 'registry.datacentred.services:5000/sal01.datacentred.co.uk/aodh:59f8f5b'
  heat:
    image: 'registry.datacentred.services:5000/sal01.datacentred.co.uk/heat:dd82cef'

telegraf::inputs:
  docker:
    endpoint: "unix:///var/run/docker.sock"

telegraf_groups:
  - 'puppet'
  - 'docker'
