---
classes:
  - '::dc_profile::openstack::nova_compute'
  - '::dc_profile::openstack::neutron_agent'
  - '::dc_profile::openstack::ceilometer_agent'
  - '::dc_icinga::hostgroup_nova_compute'

sudo::configs:
  nova:
    content: |
      Defaults: nova !requiretty
      nova ALL=(root) NOPASSWD: /usr/bin/nova-rootwrap
  neutron:
    content: |
      Defaults:neutron !requiretty, syslog_badpri=err, syslog_goodpri=info
      neutron ALL=(root) NOPASSWD: /usr/bin/neutron-rootwrap
