---
classes:
  - '::dc_profile::openstack::haproxy'
  - '::dc_profile::openstack::proxyip'
  - '::dc_profile::openstack::keepalived'

haproxy::package_ensure: '1.7.9-1ppa1~trusty'
haproxy::global_options:
        tune.bufsize: 32000
        log: '127.0.0.1 local0'
        chroot: '/var/lib/haproxy'
        pidfile: '/var/run/haproxy.pid'
        maxconn: '16000'
        user: 'haproxy'
        group: 'haproxy'
        stats: 'socket /var/lib/haproxy/stats mode 660 level user group telegraf'
        daemon: ''

telegraf::inputs:
  haproxy:
    servers:
      - "/var/lib/haproxy/stats"

filebeat::prospectors:
  haproxy:
    paths:
      - '/var/log/haproxy.log'
    doc_type: 'haproxy'
