---
classes:
  - '::dc_profile::openstack::mongodb'

mongodb::server::bind_ip: '0.0.0.0'
mongodb::server::dbpath: '/srv/mongodb'
mongodb::server::smallfiles: true
mongodb::server::replset: 'ceilometer'
mongodb::server::auth: true
mongodb::server::store_creds: true
mongodb::server::admin_username: "%{hiera('mongodb_admin_user')}"
mongodb::server::admin_password: "%{hiera('mongodb_admin_password')}"
mongodb::server::keyfile: '/etc/mongodb.keyfile'
mongodb::server::restart: false
mongodb::replset::sets:
    ceilometer:
        members:
            - "osmongodb0.%{::domain}:27017"
            - "osmongodb1.%{::domain}:27017"
            - "osmongodb2.%{::domain}:27017"

dc_profile::openstack::duplicity_mongodb::ceilometer_db_password: "%{hiera('ceilometer_db_password')}"

telegraf::inputs:
  mongodb:
    servers: ["mongodb://%{hiera('mongodb_monitor_user')}:%{hiera('mongodb_monitor_password')}@127.0.0.1:27017"]
    gather_perdb_stats: false
