---
classes:
  - '::dc_elasticsearch'
  - '::dc_elasticsearch::elasticsearch_backup_destination'

sysctls::values:
    vm.swappiness:
        value: '10'

telegraf::inputs:
  elasticsearch:
    servers:
      - 'http://localhost:9200' 
    local: true
    cluster_health: true
