---
classes:
  - '::dc_profile::log::kibana'
  - '::dc_profile::log::logstash'
  - '::dc_profile::log::riemann'
  - '::dc_profile::util::unattended_upgrades'

dc_kibana::elasticsearch_host: 'logstash'

logstash::version: '1:5.4.1-1'
logstash::restart_on_change: false
logstash::startup_options:
  'LS_GROUP': 'puppet'
