---
classes:
  - '::dc_elasticsearch'
  - '::dc_elasticsearch::elasticsearch_backup_destination'
  - '::dc_profile::util::unattended_upgrades'
  - '::dc_profile::mon::monit'

sysctls::values:
    vm.swappiness:
        value: '0'

telegraf::inputs:
  elasticsearch:
    servers:
      - 'http://localhost:9200' 
    local: true
    cluster_health: true
