---
classes:
  - '::dc_elasticsearch'
  - '::dc_elasticsearch::elasticsearch_backup_destination'

elasticsearch::version: '2.4.0'

telegraf::inputs:
  elasticsearch:
    servers:
      - 'http://localhost:9200' 
    local: true
    cluster_health: true
