---
classes:
  - 'dc_profile::perf::graphite'
  - 'dc_profile::perf::network_weathermap'
  - 'dc_profile::perf::grafana'
  - 'dc_profile::db::duplicity_mariadb'
  - 'dc_collectd::agent::openstack'

sysctls::values:
    fs.file-max:
        value: '4096000'
    net.core.rmem_max:
        value: '67108864'
    net.core.wmem_max:
        value: '67108864'
    net.core.rmem_default:
        value: '33554432'
    net.core.wmem_default:
        value: '33554432'
    net.ipv4.tcp_rmem:
        value: '16384 87380 6291456'
    net.ipv4.tcp_wmem:
        value: '16384 32768 4194304'
    net.ipv4.udp_rmem_min:
        value: '16384'
    net.ipv4.udp_wmem_min:
        value: '16384'
    net.core.optmem_max:
        value: '65536'
    net.core.somaxconn:
        value: '16384'
    net.ipv4.tcp_max_syn_backlog:
        value: '16384'
    net.core.netdev_max_backlog:
        value: '32768'
    vm.swappiness:
        value: '1'
