---
classes:
  - '::dc_profile::db::postgresql_master'

dc_postgresql::params::config_entries:
  wal_level:
    value: 'hot_standby'
  archive_mode:
    value: 'on'
  archive_command:
    value: 'cd .'
  max_wal_senders:
    value: '10'
  wal_keep_segments:
    value: '5000'
  hot_standby:
    value: 'on'
  default_statistics_target:
    value: '50'
  maintenance_work_mem:
    value: '960MB'
  constraint_exclusion:
    value: 'on'
  checkpoint_completion_target:
    value: '0.9'
  effective_cache_size:
    value: '11GB'
  work_mem:
    value: '96MB'
  wal_buffers:
    value: '8MB'
  checkpoint_segments:
    value: '16' 
  shared_buffers:
    value: '3840MB'
  max_connections:
    value: '80'
  shared_preload_libraries:
    value: 'repmgr_funcs'

dc_postgresql::repmgr::role: 'master'

dc_ssh::config:
  AllowGroups:
    value:
      - 'postgres'
