---
classes:
  - '::dc_profile::db::postgresql_master'

dc_postgresql::params::config_entries:
  wal_level:
    value: 'hot_standby'
  archive_mode:
    value: 'on'
  archive_command:
    value: 'cd .'
  max_wal_senders:
    value: '10'
  wal_keep_segments:
    value: '5000'
  hot_standby:
    value: 'on'
