---
classes:
  - '::dc_profile::puppet::puppet_master'

puppet::conf:
  agent:
    server: "puppet.%{domain}"
  master:
    vardir: '/opt/puppetlabs/server/data/puppetserver'
    logdir: '/var/log/puppetlabs/puppetserver'
    rundir: '/var/run/puppetlabs/puppetserver'
    pidfile: '/var/run/puppetlabs/puppetserver/puppetserver.pid'
    codedir: '/etc/puppetlabs/code'
    storeconfigs: 'true'
    storeconfigs_backend: 'puppetdb'
    node_terminus: 'exec'
    external_nodes: '/etc/puppetlabs/puppet/node.rb'
    reports: 'foreman'

puppet::hiera: |
  :backends:
    - eyaml
    - yaml
  :yaml:
    :datadir: "/etc/puppetlabs/code/environments/%%{}{environment}/hieradata"
  :eyaml:
    :extension: yaml
    :datadir: "/etc/puppetlabs/code/environments/%%{}{environment}/hieradata"
    :pkcs7_private_key: /etc/puppetlabs/puppet/keys/private_key.pkcs7.pem
    :pkcs7_public_key: /etc/puppetlabs/puppet/keys/public_key.pkcs7.pem
  :merge_behavior: deeper
  :hierarchy:
    - "nodes/%%{}{fqdn}"
    - "skus/%%{}{sku}"
    - "platforms/%%{}{productname}"
    - "%%{}{virtual}/architectures/%%{}{architecture}"
    - "environments/%%{}{environment}/roles/%%{}{role}"
    - "domains/%%{}{domain}/roles/%%{}{role}"
    - "roles/%%{}{role}"
    - "releases/%%{}{lsbdistcodename}/%%{}{architecture}/%%{}{calling_module}"
    - "osfamilies/%%{}{osfamily}"
    - "%%{}{environment}"
    - "environments/%%{}{environment}/modules/%%{}{calling_module}"
    - "domains/%%{}{domain}"
    - "domains/%%{}{domain}/modules/%%{}{calling_module}"
    - "modules/%%{}{calling_module}"
    - common

foreman_proxy::http: false
foreman_proxy::puppet: true
foreman_proxy::puppetca: true
foreman_proxy::puppet_group: 'puppet'
foreman_proxy::templates: false
foreman_proxy::tftp: false
foreman_proxy::dhcp: false
foreman_proxy::dns: false
foreman_proxy::bmc: false

puppetdeploy::is_puppet_master: true

dc_ssh::config:
  AllowGroups:
    value:
      - 'puppet'
