---
classes:
  - '::dc_profile::puppet::puppet_ca'
  - '::dc_profile::puppet::puppet_master'

puppet::conf:
  master:
    environmentpath: '$confdir/environments'
    node_terminus: 'exec'
    external_nodes: '/etc/puppet/node.rb'
    reports: 'foreman'
    storeconfigs: 'true'
    storeconfigs_backend: 'puppetdb'

puppet::hiera: |
  :backends:
    - eyaml
    - yaml
    - puppetdb
  :yaml:
    :datadir: "/etc/puppet/environments/%%{}{environment}/hieradata"
  :eyaml:
    :extension: yaml
    :datadir: "/etc/puppet/environments/%%{}{environment}/hieradata"
    :pkcs7_private_key: /etc/puppet/keys/private_key.pkcs7.pem
    :pkcs7_public_key: /etc/puppet/keys/public_key.pkcs7.pem
  :merge_behavior: deeper
  :hierarchy:
    - "nodes/%%{}{hostname}"
    - "skus/%%{}{sku}"
    - "platforms/%%{}{productname}"
    - "%%{}{virtual}/architectures/%%{}{architecture}"
    - "environments/%%{}{environment}/roles/%%{}{role}"
    - "domains/%%{}{domain}/roles/%%{}{role}"
    - "roles/%%{}{role}"
    - "releases/%%{}{lsbdistcodename}/%%{}{architecture}/%%{}{calling_module}"
    - "osfamilies/%%{}{osfamily}"
    - "%%{}{environment}"
    - "environments/%%{}{environment}/modules/%%{}{calling_module}"
    - "domains/%%{}{domain}"
    - "domains/%%{}{domain}/modules/%%{}{calling_module}"
    - "modules/%%{}{calling_module}"
    - "puppetversion/%%{}{puppet_major_version}"
    - common

foreman_proxy::http: false
foreman_proxy::puppet: true
foreman_proxy::puppetca: true
foreman_proxy::puppetca_cmd: '/usr/bin/puppet cert'
foreman_proxy::puppet_group: 'puppet'
foreman_proxy::templates: false
foreman_proxy::tftp: false
foreman_proxy::dhcp: false
foreman_proxy::dns: false
foreman_proxy::bmc: false

sysctls::values:
  fs.inotify.max_user_watches:
    value: '524288'

puppetdeploy::is_puppet_ca: true
puppetdeploy::puppet_masters:
  - 'puppet0'

dc_ssh::config:
  AllowGroups:
    value:
      - 'puppet'
