---
classes:
  - '::dc_profile::puppet::puppet_ca'
  - '::dc_profile::puppet::puppet_master'

puppet::conf:
  main:
    logdir: '/var/lib/puppet'
    vardir: '/var/lib/puppet'
    ssldir: '/var/lib/puppet/ssl'
    rundir: '/var/run/puppet'
    show_diff: 'true'
  master:
    environmentpath: '$confdir/environments'
    node_terminus: 'exec'
    external_nodes: '/etc/puppet/node.rb'
    reports: 'foreman'
    storeconfigs: 'true'
    storeconfigs_backend: 'puppetdb'

puppet::hiera: |
  :backends:
    - eyaml
    - yaml
    - puppetdb
  :yaml:
    :datadir: "/etc/puppet/environments/%%{}{environment}/hieradata"
  :eyaml:
    :extension: yaml
    :datadir: "/etc/puppet/environments/%%{}{environment}/hieradata"
    :pkcs7_private_key: /etc/puppet/keys/private_key.pkcs7.pem
    :pkcs7_public_key: /etc/puppet/keys/public_key.pkcs7.pem
  :merge_behavior: deeper
  :hierarchy:
    - "nodes/%%{}{hostname}"
    - "platforms/%%{}{productname}"
    - "%%{}{virtual}/architectures/%%{}{architecture}"
    - "environments/%%{}{environment}/roles/%%{}{role}"
    - "domains/%%{}{domain}/roles/%%{}{role}"
    - "roles/%%{}{role}"
    - "releases/%%{}{lsbdistcodename}/%%{}{architecture}/%%{}{calling_module}"
    - "osfamilies/%%{}{osfamily}"
    - "%%{}{environment}"
    - "environments/%%{}{environment}/modules/%%{}{calling_module}"
    - "domains/%%{}{domain}"
    - "domains/%%{}{domain}/modules/%%{}{calling_module}"
    - "modules/%%{}{calling_module}"
    - common

dc_foreman_proxy::use_puppetca: true
dc_foreman_proxy::use_puppet: true
dc_foreman_proxy::use_bmc: true

sysctls::values:
  fs.inotify.max_user_watches:
    value: '524288'

puppetdeploy::is_puppet_ca: true
puppetdeploy::puppet_masters:
  - 'puppet0'
