classes: 
  - '::dc_profile::util::wordpress'
  - '::dc_profile::util::wordpress_memcache'

nginx::nginx_locations:
  'datacentred':
    server: 'datacentred'
    location: '~* \.php$'
    fastcgi: 'unix:/var/run/php7-fpm.sock'
    www_root: '/srv/www/datacentred.co.uk'

nginx::nginx_servers:
  'datacentred':
    server_name: 
      - 'datacentred.co.uk'
      - 'datacentred.io'
      - 'datacentred.net'
      - 'datacentred.com'
      - 'datacentred.org'
      - 'datacentred.org.uk'
      - 'www.datacentred.co.uk'
      - 'www.datacentred.io'
      - 'www.datacentred.net'
      - 'www.datacentred.com'
      - 'www.datacentred.org'
      - 'www.datacentred.org.uk'
    try_files: 
      - '$uri'
      - '$uri/'
      - '/index.html'
      - '/index.php?$query_string'
    index_files: 
      - 'index.php'
      - 'index.html'
      - 'index.htm'
    www_root: '/srv/www/datacentred.co.uk'

wordpress::wp_table_prefix: 'wp_new_'
wordpress::db_name: 'datac_wp'
wordpress::db_user: 'datac_db'
wordpress::install_dir: '/srv/www/datacentred.co.uk/wordpress/'
wordpress::db_password: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAKKPTTeWNY9bTI1o1NBQtvUiOusYwGdXP1umA1VWqPfPlG/MyB6m/w6Ckpb5zAsvaqgvQ8vMkvBx5Dzl2AaVX/yMhfNcMMq075GEH/7ODjqSUcGRcVwsbpKEGV5LAXFMj3+NlzfCGHu6Ygz2TYVsvDiPM43uaqYTur6hol4udhgaAzF2g2qz7mZY/1NprSydcwPJfTAHFyJfip9W/FET7LMZnRT8hMTdUPRO4DswWtYRPhcU4M+K0Az45T3uUhLzNaPa/9ieejnGCDrMBIUzQ1lqYQIJ6FRw4VT2iZjkLSf+KiesdmjSzZ7/eEqHLzQlKZkaJ7nHYhn9lrA6uFoFM/DA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAGJtnbIr97OMDCEoTOiz+ugBBi3wQOVeEGhsd7sU2oPAbE]

php::globals::php_version: '7.0'
php::manage_repos: true
php::fpm: true
php::fpm_user: 'www-data'
php::fpm_group: 'www-data'
php::fpm::pools:
  www:
    listen: '/var/run/php7-fpm.sock'
    listen_owner: 'www-data'
    listen_group: 'www-data'
    listen_mode: '0660'
    listen_allowed_clients: 'any'
php::extensions:
  mysql: {}
