classes: 
  - '::dc_profile::util::wordpress'
  - '::dc_profile::util::wordpress::memcache'
  - '::dc_profile::util::wordpress::ssl'

nginx::nginx_locations:
  'datacentred-ssl':
    server: 'datacentred-ssl'
    location: '~* \.php$'
    fastcgi: 'unix:/var/run/php7-fpm.sock'
    www_root: '/srv/www/datacentred.co.uk'

nginx::nginx_servers:
  'datacentred-http-redirect':
    server_name:
      - 'datacentred.co.uk'
      - 'datacentred.io'
      - 'datacentred.net'
      - 'datacentred.com'
      - 'datacentred.org'
      - 'datacentred.org.uk'
      - 'www.datacentred.co.uk'
      - 'www.datacentred.io'
      - 'www.datacentred.net'
      - 'www.datacentred.com'
      - 'www.datacentred.org'
      - 'www.datacentred.org.uk'
    listen_port: '80'
    ssl: false
    ssl_redirect: true
    use_default_location: false
    ipv6_enable: false
  'datacentred-ssl':
    ssl: true
    ssl_cert: '/etc/letsencrypt/live/www.datacentred.co.uk/fullchain.pem'
    ssl_key: '/etc/letsencrypt/live/www.datacentred.co.uk/privkey.pem' 
    ssl_ciphers: 'EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5'
    ssl_session_timeout: 10m
    ssl_session_tickets: off
    ssl_stapling: true
    ssl_stapling_verify: true
    ssl_dhparam: '/etc/ssl/private/dhparam2048.pem'
    server_cfg_ssl_prepend:
      ssl_session_cache: shared:SSL:10m
      ssl_ecdh_curve: secp384r1
      large_client_header_buffers: 4 16k
    http2: 'on'
    ipv6_enable: false
    server_name:
      - 'datacentred.co.uk'
      - 'datacentred.io'
      - 'datacentred.net'
      - 'datacentred.com'
      - 'datacentred.org'
      - 'datacentred.org.uk'
      - 'www.datacentred.co.uk'
      - 'www.datacentred.io'
      - 'www.datacentred.net'
      - 'www.datacentred.com'
      - 'www.datacentred.org'
      - 'www.datacentred.org.uk'
    try_files:
      - '$uri'
      - '$uri/'
      - '/index.html'
      - '/index.php?$query_string'
    index_files:
      - 'index.php'
      - 'index.html'
      - 'index.htm'
    www_root: '/srv/www/datacentred.co.uk'

wordpress::wp_table_prefix: 'wp_new_'
wordpress::db_name: 'datac_wp'
wordpress::db_user: 'datac_db'
wordpress::install_dir: '/srv/www/datacentred.co.uk/wordpress/'
wordpress::db_password: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAKKPTTeWNY9bTI1o1NBQtvUiOusYwGdXP1umA1VWqPfPlG/MyB6m/w6Ckpb5zAsvaqgvQ8vMkvBx5Dzl2AaVX/yMhfNcMMq075GEH/7ODjqSUcGRcVwsbpKEGV5LAXFMj3+NlzfCGHu6Ygz2TYVsvDiPM43uaqYTur6hol4udhgaAzF2g2qz7mZY/1NprSydcwPJfTAHFyJfip9W/FET7LMZnRT8hMTdUPRO4DswWtYRPhcU4M+K0Az45T3uUhLzNaPa/9ieejnGCDrMBIUzQ1lqYQIJ6FRw4VT2iZjkLSf+KiesdmjSzZ7/eEqHLzQlKZkaJ7nHYhn9lrA6uFoFM/DA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAGJtnbIr97OMDCEoTOiz+ugBBi3wQOVeEGhsd7sU2oPAbE]

php::globals::php_version: '7.0'
php::manage_repos: true
php::fpm: true
php::fpm_user: 'www-data'
php::fpm_group: 'www-data'
php::fpm::pools:
  www:
    listen: '/var/run/php7-fpm.sock'
    listen_owner: 'www-data'
    listen_group: 'www-data'
    listen_mode: '0660'
    listen_allowed_clients: 'any'
php::extensions:
  mysql: {}

fail2ban::custom_jails:
  'wordpress-hard':
    findtime: '600'
    filter_includes: 'before = common.conf'
    filter_additional_config: '_daemon = wp'
    filter_failregex: |2+
      ^%(__prefix_line)sBlocked authentication attempt for .* from <HOST>$
                  ^%(__prefix_line)sBlocked user enumeration attempt from <HOST>$
                  ^%(__prefix_line)sPingback error .* generated from <HOST>$
                  ^%(__prefix_line)sSpammed comment from <HOST>$
                  ^%(__prefix_line)sXML-RPC multicall authentication failure <HOST>$
    port: 'http,https'
    logpath: '/var/log/auth.log'
    maxretry: 2
  'wordpress-soft':
    findtime: '600'
    filter_includes: 'before = common.conf'
    filter_additional_config: '_daemon = wp'
    filter_failregex: |2+
      ^%(__prefix_line)sAuthentication failure for .* from <HOST>$
                  ^%(__prefix_line)sAuthentication attempt for unknown user .* from <HOST>$
    port: 'http,https'
    logpath: '/var/log/auth.log'
    maxretry: 5
