rabbitmq::environment_variables:
    RABBITMQ_NODE_PORT: 5672
    RABBITMQ_NODE_IP_ADDRESS: "%{::ipaddress}"
    RABBITMQ_MNESIA_BASE: '/srv/rabbitmq'
    RABBITMQ_MNESIA_DIR: "/srv/rabbitmq/%{::hostname}"
